// <auto-generated />
using System;
using LightRAGNet.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightRAGNet.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522140713_AddDocumentConversionArtifacts")]
    partial class AddDocumentConversionArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LightRAGNet.Server.Models.MarkdownDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveRagTaskId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConversionCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConversionStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionTool")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionToolVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConvertedMarkdownHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConvertedMarkdownPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInRagSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PipelineCancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PipelineCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PipelineStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RagAddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RagCurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RagDocumentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RagErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RagProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("RagRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("RagStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRagTaskId");

                    b.HasIndex("ConversionStatus");

                    b.HasIndex("FileHash");

                    b.HasIndex("FileName");

                    b.HasIndex("IsInRagSystem");

                    b.HasIndex("RagDocumentId");

                    b.HasIndex("RagStatus");

                    b.HasIndex("TrackId");

                    b.ToTable("MarkdownDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
